"use client";

import { useEffect, useState } from "react";
import { Sparkles, ChevronDown, ChevronUp } from "lucide-react";
import type { AISummary as AISummaryType } from "@/lib/types";
import { cn } from "@/lib/utils";

const DIFFICULTY_COLOR: Record<string, string> = {
  Beginner: "text-emerald-600 bg-emerald-500/10 border-emerald-500/30",
  Intermediate: "text-amber-600 bg-amber-500/10 border-amber-500/30",
  Advanced: "text-rose-600 bg-rose-500/10 border-rose-500/30",
};

export function AISummary({ opportunityId, fallbackSummary }: { opportunityId: string; fallbackSummary?: string }) {
  const [summary, setSummary] = useState<AISummaryType | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);
  const [expanded, setExpanded] = useState(true);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const res = await fetch("/api/ai/summary", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ opportunityId }),
        });
        if (!res.ok) throw new Error();
        const data = await res.json();
        if (!cancelled) setSummary(data.summary);
      } catch {
        if (!cancelled) setError(true);
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();
    return () => { cancelled = true; };
  }, [opportunityId]);

  if (loading) {
    return (
      <div className="space-y-2 rounded-xl border border-line bg-base/40 p-4">
        <div className="flex items-center gap-2 text-[13px] font-semibold text-ink">
          <Sparkles size={14} className="text-purple-500 animate-pulse" /> AI Summary
        </div>
        <div className="space-y-2">
          <div className="h-3 w-full animate-pulse rounded bg-elevated" />
          <div className="h-3 w-3/4 animate-pulse rounded bg-elevated" />
          <div className="h-3 w-1/2 animate-pulse rounded bg-elevated" />
        </div>
      </div>
    );
  }

  if (error || !summary) {
    if (!fallbackSummary) return null;
    return (
      <div>
        <p className="mb-1 text-[13px] font-semibold text-ink">About</p>
        <p className="text-[13px] leading-relaxed text-ink-2">{fallbackSummary}</p>
      </div>
    );
  }

  return (
    <div className="rounded-xl border border-purple-500/20 bg-purple-500/[0.03] p-4">
      <button
        onClick={() => setExpanded((v) => !v)}
        className="flex w-full items-center justify-between gap-2"
      >
        <span className="flex items-center gap-2 text-[13px] font-semibold text-ink">
          <Sparkles size={14} className="text-purple-500" /> AI Summary
        </span>
        {expanded ? <ChevronUp size={14} className="text-ink-3" /> : <ChevronDown size={14} className="text-ink-3" />}
      </button>

      {expanded && (
        <div className="mt-3 space-y-3">
          <SummaryField label="What it's about" value={summary.what} />
          <SummaryField label="Who should apply" value={summary.whoShouldApply} />
          <SummaryField label="Key eligibility" value={summary.keyEligibility} />

          {summary.skillsRequired.length > 0 && (
            <div>
              <p className="mb-1 text-[11px] font-semibold uppercase tracking-wide text-ink-3">Skills required</p>
              <div className="flex flex-wrap gap-1.5">
                {summary.skillsRequired.map((s, i) => (
                  <span key={i} className="rounded-md border border-line bg-elevated px-2 py-0.5 text-[11px] text-ink-2">
                    {s}
                  </span>
                ))}
              </div>
            </div>
          )}

          <SummaryField label="Benefits" value={summary.benefits} />
          <SummaryField label="Deadlines" value={summary.importantDeadlines} />

          <div className="flex items-center gap-2">
            <span className="text-[11px] font-semibold uppercase tracking-wide text-ink-3">Difficulty</span>
            <span className={cn("rounded-full border px-2 py-0.5 text-[11px] font-semibold", DIFFICULTY_COLOR[summary.estimatedDifficulty] ?? "text-ink-2 bg-elevated border-line")}>
              {summary.estimatedDifficulty}
            </span>
          </div>

          <p className="text-[10px] text-ink-3">✨ Generated by AI · may not be perfectly accurate</p>
        </div>
      )}
    </div>
  );
}

function SummaryField({ label, value }: { label: string; value: string }) {
  if (!value || value === "Not specified") return null;
  return (
    <div>
      <p className="mb-0.5 text-[11px] font-semibold uppercase tracking-wide text-ink-3">{label}</p>
      <p className="text-[13px] leading-relaxed text-ink-2">{value}</p>
    </div>
  );
}
